# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: double_pinyin_flypy
  # - schema: luna_pinyin_simp

switcher:
  caption: 「方案选单」
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options: # 开关记忆（方案中的 switches），从方案选单（而非快捷键）切换时会记住的选项，需要记忆的开关不能设定 reset
    - ascii_punct
    - traditionalization
    - emoji
    - full_shape
    - search_single_char
  fold_options: true # 呼出时是否折叠，多方案时建议折叠 true ，一个方案建议展开 false
  abbreviate_options: true # 折叠时是否缩写选项
  option_list_separator: ' / ' # 折叠时的选项分隔符

menu:
  page_size: 9

punctuator:
  full_shape:
    ' ': { commit: '　' }
    ',': { commit: ， }
    '.': { commit: 。 }
    '<': [《, 〈, «, ‹]
    '>': [》, 〉, », ›]
    '/': [／, ÷]
    '?': { commit: ？ }
    ';': { commit: ； }
    ':': { commit: ： }
    "'": { pair: ['‘', '’'] }
    '"': { pair: ['“', '”'] }
    '\': [、, ＼]
    '|': [·, ｜, '§', '¦']
    '`': ｀
    '~': ～
    '!': { commit: ！ }
    '@': [＠, ☯]
    '#': [＃, ⌘]
    '%': [％, '°', '℃']
    '$': [￥, '$', '€', '£', '¥', '¢', '¤']
    '^': { commit: …… }
    '&': ＆
    '*': [＊, ·, ・, ×, ※, ❂]
    '(': （
    ')': ）
    '-': －
    '_': ——
    '+': ＋
    '=': ＝
    '[': [「, 【, 〔, ［]
    ']': [」, 】, 〕, ］]
    '{': [『, 〖, ｛]
    '}': [』, 〗, ｝]
  half_shape:
    ',': '，'
    '.': '。'
    '<': '《'
    '>': '》'
    '/': '/'
    '?': '？'
    ';': '；'
    ':': '：'
    "'": { pair: ['‘', '’'] }
    '"': { pair: ['“', '”'] }
    '\': '、'
    '|': '|'
    '`': '`'
    '~': '~'
    '!': '！'
    '@': '@'
    '#': '#'
    '%': '%'
    '$': '¥'
    '^': '……'
    '&': '&'
    '*': '*'
    '(': '（'
    ')': '）'
    '-': '-'
    '_': ——
    '+': '+'
    '=': '='
    '[': '【'
    ']': '】'
    '{': '「'
    '}': '」'

key_binder:
  bindings:
    - { accept: 'Control+space', toggle: ascii_mode, when: always }
    - { accept: 'Escape', send: Caps_Lock, when: has_menu }
    - { accept: 'Shift+BackSpace', send: Escape, when: has_menu }
#     __patch:
#       - key_bindings:/emacs_editing
#       - key_bindings:/move_by_word_with_tab
#       - key_bindings:/paging_with_minus_equal
#       - key_bindings:/paging_with_comma_period
#       - key_bindings:/numbered_mode_switch

recognizer:
  patterns:
    email: '^[A-Za-z][-_.0-9A-Za-z]*@.*$' # email @ 之后不上屏
    url: '^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$' # URL
    underscore: '^[A-Za-z]+_.*' # 下划线不上屏
    # url_2: "^[A-Za-z]+[.].*"   # 句号不上屏，支持 google.com abc.txt 等网址或文件名，使用句号翻页时需要注释掉
    # colon: "^[A-Za-z]+:.*"     # 冒号不上屏

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: commit_code
    # Shift_L: inline_ascii
    # Shift_R: commit_text
    # Control_L: noop
    # Control_R: noop
    # Caps_Lock: clear
    # Eisu_toggle: clear
